serviceAccounts:
  alertmanager:
    create: false
  nodeExporter:
    create: false
  pushgateway:
    create: false
  server:
    create: true

nodeExporter:
  enabled: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

forceNamespace: gossipqa-metrics

server:
  enabled: true
  retention: "365d"
  # persistentVolume:
  #   existingClaim: "gossipqa-prom-pvc"




    # size: 1000Gi
    # storageClass: ssd-retain
  

grafana:
  extraConfigmapMounts: 
  - name: simplified-mainnet-dashboard
    mountPath: /var/lib/grafana/dashboards
    configMap: simplified-mainnet-dashboard
    readOnly: true